# to connect DVC stages and  parameters

stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    # - data/raw/reddit.csv
    params:
    - data_ingestion.test_size
    outs:
    - data/interim

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/interim/train.csv
    - data/interim/test.csv
    - src/data/data_preprocessing.py
    outs:
    - data/processed

  model_building:
    cmd: python src/models/model_building.py
    deps:
    - data/processed/train_processed.csv
    - src/models/model_building.py
    params:
    - model_building.max_features
    - model_building.ngram_range
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    outs:
    - models/lgbm_model.pkl
    - models/tfidf_vectorizer.pkl

  model_evaluation:
    cmd: python src/models/model_evaluation.py
    deps:
    - models/lgbm_model.pkl
    - models/tfidf_vectorizer.pkl
    - data/processed/train_processed.csv
    - data/processed/test_processed.csv
    - src/models/model_evaluation.py
    outs:
    - logs/experiment_info.json

  model_registration:
    cmd: python src/models/register_model.py
    deps:
    - logs/experiment_info.json
    - src/models/register_model.py